---USER DETAILS TABLE---
create table user_details( user_id int generated by default as identity (start with 100 increment by 1) primary key,
                           user_name varchar2(20) default 'user'
                          ,email_id varchar2(90)unique not null,
                          password varchar2(20)not null,
                          address varchar2(200)not null,
                          user_wallet number  default '50000');                     

insert into user_details (user_name,email_id,password,address,role) values ('Atchaya','atchaya10@gmail.com','atchayapandi','Madurai','Admin');

---Table 2: Help and Support

create table help_support (phone number(15),Email varchar2(100));
insert into help_support values(8610970796,'atchaya10@gmail.com');

update help_support set  Email='atchaya1011@gmail.com' where phone=9600939198;


--- Table 3 : PRODUCT DETAILS TABLE---
create table product_details(cake_id int default P_ID.nextval primary key ,
                      cake_name varchar2(30)not null,
                      cake_description varchar2(100)not null,
                      cake_price int not null,
                      category_name varchar2(20)not null,
                      picture varchar2(200) not null,
                      rating number(5,2) default 5,
                      rating_count number default 0); 
                      
                        
create sequence P_ID increment by 1 start with 111;  
update product_details set rating_count default 1;

alter table product_details modify rating_count default 1;

insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values ('Truffle Cake' ,'made with a chocolate ganache centre coated in chocolate',1025,'butter');
insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values ('Butterscotch Cake','The cake layers are made with brown sugar which is the primary ingredient of butterscotch',1030,'chocolate');
insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values ('Black Forest Cake','chocolate sponge cake, cherries, and whipped cream',1050,'Biscuit');
insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values ('Fresh Fruit Cake','cake made with chopped candied fruit and/or dried fruit, nuts, and spices',1900,'Baked Flourless Cake');
insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values ('Pinapple Cake','scratch with crushed pineapple and topped',1500,'Sponge Cake');
insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values ('Caramel Cake','Salted Caramel',1700,'Genoise Cake');
insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values('Strawberry Cake',' scone that is split and filled with strawberries and sweetened whipped cream',2000,'pound cake');
insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values('Oreo Cake',' caramel flavour filling and coloured sprinkles',1300,'Sponge Cake');
insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values('Blueberry','butter and dust with flour and line the bottom with parchment paper',1400,'butter');
insert into product_details (cake_name,cake_description,cake_price,category_name,picture) values('White Forest','white cake with vanilla extract in the mixture',1200,'Biscuit');



--- Table 4 : ORDER DETAILS TABLE---
create table cart_items(cart_id int generated BY DEFAULT AS IDENTITY (START WITH 200 INCREMENT BY 1)primary key,
                       cake_id int, 
                      user_id int,                       
                     order_quantity int not null,                    
                     total_price number(10,2) not null,
                     order_date Date not null,
                     foreign  key (cake_id) references product_details(cake_id) , 
                     foreign key (user_id) references user_details(user_id));
     
 ---Table 5 : Customized Order Details      
create table customized_details(custcake_id int generated BY DEFAULT AS IDENTITY (START WITH 500 INCREMENT BY 1)primary key,
                                 User_id int,                                
                                 flavour varchar2(100),
                                 types varchar2(100),
                                 shape varchar2(100),
                                 quantity int,
                                 Order_date Date,     
                                 Initial_amount int default 1000,
                                 foreign key (user_id) references user_details(user_id));       
                                 commit;
                                 update product_details set rating_count=1;
    
  
  
                                          
select*from help_support;
select * from cart_items; 
select * from product_details;
select * from user_details;
select*from customized_details;

commit;

